/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.NapTheDAO;
import DAO.ThongKePhanHoiDAO;
import DAO.UserDAO;
import Packet.NapTheDATA;
import Packet.ThongKePHDaTa;
import Packet.UserLib;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import snakegame.Game;

/**
 *
 * @author Hoang Minh
 */
public class Library extends javax.swing.JFrame {
 UserDAO dao = new UserDAO();
 ThongKePhanHoiDAO daomain = new ThongKePhanHoiDAO();
 NapTheDAO dao2 = new NapTheDAO();
    String duongdananh="";
    public static Library lib;
    public JLabel lbl;
    public Library() {
        initComponents();
        lib=this;
        lbl = lblUserName;
        this.setLocationRelativeTo(null);
        init();
    }
    private void init(){
        
        LoadDataToTable();
       tblLib.removeColumn(tblLib.getColumn("2"));tblLib.removeColumn(tblLib.getColumn("3"));tblLib.removeColumn(tblLib.getColumn("4"));tblLib.removeColumn(tblLib.getColumn("5"));tblLib.removeColumn(tblLib.getColumn("6"));tblLib.removeColumn(tblLib.getColumn("7"));
        int indexxx =0;
       
       try{ 
           tblLib.setRowSelectionInterval(indexxx, indexxx);
       showRecord(indexxx);
       }catch(Exception e){}
    }
    
    public void LoadDataToTable(){
        try{
        DefaultTableModel mode = (DefaultTableModel) tblLib.getModel();
        mode.setRowCount(0);
        
        List<UserLib> list = this.dao.selectAll();
        if(list ==  null){
           
            return;
        }
        for (UserLib pro : list) {
            Object[] row = new Object[]{pro.getGame() ,pro.getPrice(), pro.getTheLoai(),pro.getThongTin() 
            ,pro.getGamePic(),pro.getNPH(),pro.getIDD()};
            mode.addRow(row);
        }
        }catch(Exception e){
            System.out.println("Không có dữ liệu");
        }
    }
    public void showRecord(int k) {
        DefaultTableModel model = (DefaultTableModel) tblLib.getModel();
        if (k >= 0) {

            lblName.setText((String) model.getValueAt(k, 0));
            lblTheLoai.setText((String) model.getValueAt(k, 2));
            lblGia.setText( model.getValueAt(k, 1).toString());
            lblInfo.setText((String) model.getValueAt(k, 3));
            lblNPH.setText((String) model.getValueAt(k, 5));
            lblID.setText((String) model.getValueAt(k, 6));
            if(!model.getValueAt(k, 4).toString().equals("")){
                lblPic.setText("");
            }
            
            duongdananh=(String) model.getValueAt(k,4);
            lblPic.setIcon(ResizeImage(String.valueOf("src\\img\\"+duongdananh)));
            
            
        }

    }
    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblPic.getWidth(), lblPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLib = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblInfo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblTheLoai = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNPH = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDanhGia = new javax.swing.JTextArea();
        btnDislike = new javax.swing.JRadioButton();
        btnLike = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 388, 39));

        jButton1.setBackground(new java.awt.Color(255, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Tìm");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 90, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 153));
        jLabel2.setText("Tìm Kiếm");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 255));
        jLabel8.setText("Quay lại Store");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        tblLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Games", "2", "3", "4", "5", "6", "7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLib);
        if (tblLib.getColumnModel().getColumnCount() > 0) {
            tblLib.getColumnModel().getColumn(0).setResizable(false);
            tblLib.getColumnModel().getColumn(1).setResizable(false);
            tblLib.getColumnModel().getColumn(2).setResizable(false);
            tblLib.getColumnModel().getColumn(3).setResizable(false);
            tblLib.getColumnModel().getColumn(4).setResizable(false);
            tblLib.getColumnModel().getColumn(5).setResizable(false);
            tblLib.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 370, 470));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("NGƯỜI DÙNG:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserName.setText("jLabel11");
        jPanel2.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 720));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDel.setBackground(new java.awt.Color(255, 102, 204));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDel.setText("Hoàn Trả Game");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel3.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 130, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Game info:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 289, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("NPH");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên Game:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, -1));

        lblPic.setBackground(new java.awt.Color(204, 255, 255));
        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setText("HÌnh");
        jPanel3.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 216, 176));

        lblName.setText("...");
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 15, 235, 35));

        lblInfo.setColumns(20);
        lblInfo.setRows(5);
        jScrollPane2.setViewportView(lblInfo);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 283, 154));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Thể loại:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 95, -1, -1));

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGia.setText("Gia");
        jPanel3.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, -1));

        lblTheLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTheLoai.setText("The loai");
        jPanel3.add(lblTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Giá Game:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 201, -1, -1));

        lblNPH.setText("jLabel10");
        jPanel3.add(lblNPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        lblID.setText("HiddenID");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 102, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Play");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 119, 37));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 11, 800, 460));

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Đánh Giá:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, -1, -1));

        txtDanhGia.setColumns(20);
        txtDanhGia.setRows(5);
        jScrollPane3.setViewportView(txtDanhGia);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 33, 300, 130));

        btnDislike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDislike.setText("DisLike");
        jPanel4.add(btnDislike, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btnLike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLike.setText("Like");
        jPanel4.add(btnLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 181, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Gửi Phản hồi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 172, 114, 39));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 473, 800, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        InterFaceStore stus = new InterFaceStore();
        stus.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void tblLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibMouseClicked
        int index=0;
        index = tblLib.getSelectedRow();
        showRecord(index);
    }//GEN-LAST:event_tblLibMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String p = lblGia.getText();
        int res = JOptionPane.showConfirmDialog(this, "Bạn có muốn hoàn trả game và nhận lại "+p +"$$$");
        if(res == JOptionPane.YES_OPTION){
        String iddel =lblID.getText();
        NapTheDATA pro = getFormReturn();
        if(!iddel.equals("")){

            dao.delete(iddel);
            dao2.update(getFormReturn());       
            JOptionPane.showMessageDialog(this, "Thành công");

            LoadDataToTable();

        }else{
            System.out.println("Fail");
        }
        
       
            dao2.update(getFormReturn());       
        }
        
    }//GEN-LAST:event_btnDelActionPerformed
public NapTheDATA getFormReturn(){
        String user= lblUserName.getText();
        float money = 0;
        
        try {
             money= Float.valueOf(lblGia.getText());
        } catch (Exception e) {
            return null;
        }
        return new NapTheDATA(user,money);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Game g = new Game();
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ThongKePHDaTa pro = new ThongKePHDaTa();
        if(pro != null){
            daomain.update(getForm());
           
            JOptionPane.showMessageDialog(this, "Thành công");

        }else{
            System.out.println("Fail");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
public boolean getLikes() {
        if (btnLike.isSelected()) {
            return false;
        } else if (btnDislike.isSelected()) {
            return true;
        }
        return true;
    }
public ThongKePHDaTa getForm(){
    boolean likes = getLikes();
    String phanhoi = txtDanhGia.getText();
    String id = lblID.getText();
    String theloai =lblTheLoai.getText();
    String nph = lblNPH.getText();
    String name = lblName.getText();
    float price = 0;
        try {
             price = Float.valueOf(lblGia.getText());
        } catch (Exception e) {
            return null;
        }
        return new ThongKePHDaTa(id,name,nph,price,theloai,phanhoi,likes);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JRadioButton btnDislike;
    private javax.swing.JRadioButton btnLike;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextArea lblInfo;
    private javax.swing.JLabel lblNPH;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblTheLoai;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblLib;
    private javax.swing.JTextArea txtDanhGia;
    // End of variables declaration//GEN-END:variables
}
